name: xdg_accounts
description: A dart library implementing the DBus org.freedesktop.Accounts interface.
version: 0.0.1
homepage: https://github.com/ubuntu-flutter-community/xdg_accounts

environment:
  sdk: '>=2.18.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dbus: ^0.7.2
